---
- name: Deploy test server in NREC
  hosts: localhost

  tasks:
    - name: Create a new keypair
      tags: keypair
      openstack.cloud.keypair:
          state: present
          name: ansible-test-key
      register: keypair_result

    - name: Make dir for private key
      tags: keypair
      ansible.builtin.file:
        state: directory
        path: .ssh
        mode: 0700

    - name: Save private key file
      tags: keypair
      ansible.builtin.copy:
        content: '{{ keypair_result.keypair.private_key }}'
        dest: '.ssh/{{ keypair_result.keypair.name }}.pem'
        mode: '0600'
        backup: yes
      when: keypair_result.changed and keypair_result.keypair is defined

    - name: Create a new instance and attaches to a network # and passes metadata to the instance
      openstack.cloud.server:
           state: present
           name: ansible-test
           image: GOLD Rocky Linux 8
           key_name: ansible-test-key
           timeout: 200
           flavor: m1.small
           nics:
             - net-name: dualStack
           security_groups:
             - default
    #       meta:
    #         hostname: test1
    #         group: uge_master
      register: instance_result

    # Creates a new volume
    - name: create 10g test volume
      tags: volumes
      openstack.cloud.volume:
        state: present
        size: 10
        volume_type: mass-storage-default
        display_name: ansible_test_volume
        display_description: Volume for testing ansible

    # Attaches a volume to a compute host
    - name: attach volume to host
      tags: volumes
      openstack.cloud.server_volume:
        state: present
        server: ansible-test
        volume: ansible_test_volume

    - name: Add CentOS Instance to Inventory
      add_host: name=test-ansible
                ansible_ssh_host={{ instance_result.server.addresses.dualStack[0].addr }}
                ansible_ssh_private_key_file=.ssh/ansible-test-key.pem

- hosts: test-ansible
  remote_user: rocky
  become: true
  tasks:
    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present

    - name: create partition
      parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
        part_end: 10GB

    - name: task for creating volume group
      lvg:
        vg: sample-vg
        pvs: /dev/sdb1

    - name: task for creating logical volume
      lvol:
        vg: sample-vg
        lv: sample-lv
        size: 100%FREE
        shrink: false

    - name: Create directory data1 if does not exist
      file:
        path: /data
        state: directory
        mode: '0755'

    - name: format the xfs filesystem
      filesystem:
        fstype: xfs
        dev: /dev/sample-vg/sample-lv

    - name: mount the lv on /data1
      mount:
        path: /data
        src: /dev/sample-vg/sample-lv
        fstype: xfs
        state: mounted