all:
  children:

    webserver:
      hosts:
        ansible-test99:
          server_name: ansible-test99
          ansible_user: rocky
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/jaspar
          volume_size: 60
          dns_usage: true
          dns_zone_name: jaspar.uiocloud.no
          dns_zone_subdomain: test99.jaspar.uiocloud.no
          ansible_ssh_host: test99.jaspar.uiocloud.no
          add_instance_security: true
          port_list:
            - 80
            - 443
          security_group_name: jaspar-test99
          admin_email: jeannech@uio.no
          smtp_host: smtp.uio.no
          smtp_user: nobody
          smtp_password: ''




