all:
  children:
    webserver:
      hosts:
        jaspar-dev:
          server_name: '{{ server_name_cmd }}'
          volume_name: '{{ server_name_cmd }}-volume'
          ansible_user: rocky
          server_flavor: m1.xlarge
          ansible_ssh_private_key_file: .ssh/jaspar-dev.pem
          volume_size: 60
          dns_usage: true
          dns_zone_name: '{{ ansible_dns_zone_cmd | default("uio-elixir-devops.uiocloud.no")}}'
          ansible_ssh_host: '{{ ansible_ssh_host_cmd | default("jaspar-test.uio-elixir-devops.uiocloud.no")}}'
          dns_zone_subdomain: '{{ ansible_ssh_host }}'
#          add_instance_security: true
          port_list:
            - 80
            - 443
            - 22
          security_group_name: webserver
#          admin_email: jeannech@uio.no
#          smtp_host: smtp.uio.no
#          smtp_user: nobody
#          smtp_password: ''
          jaspar_base_dir: /data/www/apps
          jaspar_data_dir: /data/tmp/jaspar-data
          ldap_uri: ldap.uio-elixir-devops.uiocloud.no
          ldap_dn: 'cn=admin,dc=ldap,dc=uio-elixir-devops,dc=uiocloud,dc=no'
          jaspar_secure: true

