all:
  children:
    webserver:
      hosts:
        jaspar-dev:
          server_name: '{{ server_name_test }}'
          volume_name: '{{ server_name_test }}-volume'
          ansible_user: rocky
          ansible_ssh_private_key_file: .ssh/jaspar-dev.pem
          volume_size: 60
          dns_usage: true
          dns_zone_name: uio-elixir-devops.uiocloud.no
          ansible_ssh_host: '{{ ansible_ssh_host_temp | default("jaspar-test.uio-elixir-devops.uiocloud.no")}}'
          dns_zone_subdomain: '{{ ansible_ssh_host }}'
#          add_instance_security: true
          port_list:
            - 80
            - 443
            - 22
          security_group_name: webserver
#          admin_email: jeannech@uio.no
#          smtp_host: smtp.uio.no
#          smtp_user: nobody
#          smtp_password: ''
          jaspar_base_dir: /data/www/apps
          jaspar_data_dir: /data/tmp/jaspar-data
          ldap_uri: ldap.uio-elixir-devops.uiocloud.no
          ldap_dn: 'cn=admin,dc=ldap,dc=uio-elixir-devops,dc=uiocloud,dc=no'


#
#
#dc=ldap,dc=uio-elixir-devops,dc=uiocloud,dc=no
#
#(test_ansible) jeannech@Jeannes-MacBook-Pro ansible-playbook-jaspar % ldapsearch -x -b "dc=ldap,dc=uio-elixir-devops,dc=uiocloud,dc=no" -H ldap.uio-elixir-devops.uiocloud.no
#
#ldapsearch -H ldap://ldap.uio-elixir-devops.uiocloud.no -x -D "dc=ldap,dc=uio-elixir-devops,dc=uiocloud,dc=no" -w bX63Kp$7vCBu -b "dc=ldap,dc=uio-elixir-devops,dc=uiocloud,dc=no"
#
# ldapsearch -H ldap://ldap.uio-elixir-devops.uiocloud.no -x -D "cn=admin,dc=example,dc=com" -w password -b "dc=example,dc=com"
# ldapsearch -H ldap://ldap.uio-elixir-devops.uiocloud.no -x -b "dc=ldap,dc=uio-elixir-devops,dc=uiocloud,dc=no"