jaspar_web:
  hosts:
    test.jaspar.uiocloud.no:
      ansible_dns: jaspar.uiocloud.no.
      ansible_user: cloud-user
      ansible_ssh_private_key_file: ~/.ssh/jaspar-test-key.pem
      jaspar_base_dir: /data/jaspar
      jaspar_data_dir: /data/JASPAR_RELEASES_2022-02-11
      jaspar_data_url: 'https://frigg.uio.no/ftp/mathelier/JASPAR_RELEASES_2022-02-11/'
      admin_email: morj@ifi.uio.no
      smtp_host: smtp.uio.no
      smtp_user: nobody
      smtp_password: ''

    test2.jaspar.uiocloud.no:
      ansible_user: rocky
      ansible_ssh_private_key_file: ~/.ssh/ansible-test3-key.pem
      ansible_dns: jaspar.uiocloud.no.
      jaspar_base_dir: /data/jaspar
      jaspar_data_dir: /data/JASPAR_RELEASES_2022-02-11
      jaspar_data_url: 'https://frigg.uio.no/ftp/mathelier/JASPAR_RELEASES_2022-02-11/'
      admin_email: jeannech@uio.no
      smtp_host: smtp.uio.no
      smtp_user: nobody
      smtp_password: ''

    test4.jaspar.uiocloud.no:
      ansible_user: rocky
      ansible_ssh_private_key_file: .ssh/ansible-test4-key.pem
      ansible_dns: jaspar.uiocloud.no.
      #jaspar_base_dir: /data/jaspar
      #jaspar_data_dir: /data/JASPAR_RELEASES_2022-02-11
      #jaspar_data_url: 'https://frigg.uio.no/ftp/mathelier/JASPAR_RELEASES_2022-02-11/'
      admin_email: morj@uio.no
      #smtp_host: smtp.uio.no
      #smtp_user: nobody
      #smtp_password: ''
