all:
  children:
    webserver:
      hosts:
        jaspar-dev:
          server_name: '{{ server_name_cmd }}'
          volume_name: '{{ server_name_cmd }}-volume'
          server_flavor: m1.xlarge
          ansible_host: '{{ ansible_ssh_host_cmd | default("jaspar-test.uio-elixir-devops.uiocloud.no")}}'
          ansible_private_key_file: .ssh/{{ server_name_cmd }}.pem
          ansible_python_interpreter: /usr/bin/python
          ansible_user: rocky
          volume_size: 60
          dns_usage: true
          dns_zone_name: '{{ ansible_dns_zone_cmd | default("uio-elixir-devops.uiocloud.no")}}'
          elixir_main_dns: jaspar.elixir.no
          elixir_dns:
            - 'jaspar.elixir.no'
            - 'jaspar2022.elixir.no'
            - 'jaspar2020.elixir.no'
          dns_zone_subdomain: '{{ ansible_host }}'
#          add_instance_security: true
          port_list:
            - 80
            - 443
          security_group_name: webserver
#          admin_email: jeannech@uio.no
#          smtp_host: smtp.uio.no
#          smtp_user: nobody
#          smtp_password: ''
          jaspar_base_dir: /data/www/apps
          jaspar_data_dir: /data/tmp/jaspar-data
          ldap_uri: ldap.uio-elixir-devops.uiocloud.no
          ldap_dn: 'cn=admin,dc=ldap,dc=uio-elixir-devops,dc=uiocloud,dc=no'
          jaspar_secure: true
          jaspar_profile_inference_version:
            - year: 2020
              jaspar_profile_inference_git_version: faa660497f6a222c22f3aa42db992a5f70f84b4b
            - year: 2022
              jaspar_profile_inference_git_version: 5fa64a79c79763384b484d9345bf112bd7dcbf11
            - year: common
              jaspar_profile_inference_git_version: master


