---
roles:
  - role: ansible-role-setup-nrec
    src: ssh://git@github.com/elixir-oslo-devops/ansible-role-setup-nrec.git
    version: dev-jaspar
    scm: git
  - role: ansible-role-setup-nrec-host
    src: ssh://git@github.com/elixir-oslo-devops/ansible-role-setup-nrec-host.git
    version: dev-jaspar
    scm: git

collections:
  - name: openstack.cloud
    version: 2.3.3
