---
# defaults file for setup-nrec
server_name: ansible-test
image:
  rocky:
    gold_name: GOLD Rocky Linux 8
  cloud-user:
    gold_name: UiO Managed RHEL 8
  ubuntu:
    gold_name: Ubuntu 22.04 LTS
keypair_name: '{{ server_name }}-key'
volume_name: '{{ server_name }}-volume'
volume_size: 10
ipv4_list:
  - 193.157.244.10 # Nemko building
  - 129.240.0.0/16 # All UIO
  - 84.210.213.155 # Perso IP adress
