---
# tasks file for 04-user-django-patches

#TODO: Ansiblelized script ?
- name:  A simplistic substitution for Python version adjustments.
  become: false
  ansible.builtin.command:
    cmd: '{{ jaspar_app_dir }}/deploy/04-user-django-patches.sh'
    chdir: '{{ jaspar_app_dir }}'
