---
# tasks file for 06-user-clustering

#TODO: Ansiblelized script ?
- name: Find collections of clustering resources to process.
  become: false
  ansible.builtin.command:
    cmd: '{{ jaspar_app_dir }}/deploy/06-user-clustering.sh'
    chdir: '{{ jaspar_app_dir }}'