---
# tasks file for 11-root-httpd

##TODO: Ansiblelized script ?
#- name: Obtain any site identifier and use that instead of the default.
#  become: true
#  ansible.builtin.command:
#    cmd: '{{ jaspar_app_dir }}/deploy/11-root-httpd.sh'
#    chdir: '{{ jaspar_app_dir }}'
#


- name: List WSGI files
  tags:
    - httpd
  ansible.builtin.find:
    path: '{{ jaspar_app_dir }}/jaspar'
    file_type: file
    patterns: 'wsgi*.py'
  register: jaspar_wsgi


- name: Restore default SELinux security contexts for static dir
  tags:
    - httpd
  become: true
  ansible.builtin.command:
    cmd: '{{ jaspar_app_dir }}/deploy/tools/init_site {{ ansible_ssh_host }} {{ item | basename |  split(".") | first | regex_replace("^[a-z]+", "")}}'
  loop: '{{ jaspar_wsgi.files  | map(attribute="path") }}'



- name: test
  tags:
    - test_replace
  become: true
  ansible.builtin.debug:
    msg: '{{ apache_modules_directory[ansible_user] }}'