---
# tasks file for 11-root-httpd

#TODO: Ansiblelized script ?
- name: Obtain any site identifier and use that instead of the default.
  become: true
  ansible.builtin.command:
    cmd: '{{ jaspar_app_dir }}/deploy/11-root-httpd.sh'
    chdir: '{{ jaspar_app_dir }}'