---
# tasks file for 15-django-q-cluster

- name: Start django-q cluster
  become: true
  become_user: apache
  tags:
    - jaspar
    - 15-django-q-cluster
  ansible.builtin.shell:
    cmd: |
      RELEASE_YEAR=$(grep -oiP 'RELEASE\s*=\s*"?\K[0-9]+' jaspar/wsgi.py)
      export DJANGO_SETTINGS_MODULE="jaspar.settings${RELEASE_YEAR}"
      nohup python {{ jaspar_app_dir }}/manage.py qcluster >/tmp/qcluster.log 2>&1 &
      sleep 5
    chdir: '{{ jaspar_app_dir }}'
  environment:
    PYTHONPATH: '{{ pythonpath.stdout }}'
