---
# tasks file for jaspar
- name: Install EPEL repo
  tags:
    - jaspar
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: latest
  when: ansible_user == 'rocky'


- name: Install prerequisite
  tags:
    - jaspar
    - package-installation
  become: true
  ansible.builtin.package:
    state: present
    update_cache: true
  loop:
    - python3-pip
    - certbot
    - python3-certbot-apache
    - mod_ssl
  when: ansible_user == 'rocky'
