---
# tasks file for jaspar
- name: Install prerequisite
  tags:
    - jaspar
    - package-installation
  become: true
  ansible.builtin.package:
    state: present
    update_cache: true
  loop:
    - python3-pip
    - certbot
    - python3-certbot-apache
  when: ansible_user == 'rocky'
