---

- name: Install packages
  become: yes
  ansible.builtin.package:
    state: present
    name:
      - git
      - httpd
      - certbot
      - python3-certbot-apache
      - wget
      - conda

- name: Make base directory
  become: yes
  ansible.builtin.file:
    state: directory
    path: '{{ jaspar_base_dir }}'
    owner: '{{ ansible_user }}'
    mode: 0755
    recurse: no
    #setype: 'httpd_sys_content_t'


- name: Certbot account register
  become: yes
  ansible.builtin.command:
    cmd: 'certbot -n register --agree-tos --email {{ admin_email }}'
    creates: '/etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/*/regr.json'

- name: Clone main repo
  ansible.builtin.git:
    repo: 'https://bitbucket.org/CBGR/jaspar2020.git'
    dest: '{{ jaspar_base_dir }}/jaspar2020'
    version: '20211214-buildah-deployment'
    update: no

- name: Clone branding repo
  ansible.builtin.git:
    repo: 'https://bitbucket.org/CBGR/jaspar-branding.git'
    dest: '{{ jaspar_base_dir }}/jaspar-branding'

# Loops through list of files/dirs to label, using regex to create regex.
# Takes a minute, probably due to checking the state of every item
- name: Set SELinux file context for httpd
  tags: selinux
  become: yes
  community.general.sefcontext:
    target: '{{ jaspar_base_dir }}/{{ item | regex_replace("/$", "(/.*)?") }}'
    setype: httpd_sys_content_t
    state: present
  loop: '{{ sef_httpd_content }}'
  register: sefcontext

# Apply label to given file/dir only if changed in the above task. Yes it works.
- name: Apply SELinux file contexts
  tags: selinux
  become: yes
  ansible.builtin.command: 'restorecon -ir {{ jaspar_base_dir }}/{{ item.item }}'
  when: item.changed
  loop: '{{ sefcontext.results }}'

# builtin.get_url not appear to support recursive download
- name: Fetch JASPAR data
  tags: fetch-data
  ansible.builtin.command:
    cmd: 'wget -r -nv -nc -nd -np -l 1 --no-check-certificate -e robots=off -P {{ jaspar_data_dir }} {{ jaspar_data_url }} '
  register: wget_result
  changed_when: '"Downloaded:" in wget_result.stderr'

- name: SMTP settings file
  ansible.builtin.template:
    src: templates/smtp_settings.txt.j2
    dest: '{{ jaspar_base_dir }}/jaspar2020/smtp_settings.txt'
    #setype: httpd_sys_content_t

- name: Update settings
  tags: settings
  ansible.builtin.replace:
    path: '{{ jaspar_base_dir }}/jaspar2020/jaspar/settings.py'
    regexp: '^{{ item.setting }} = .+'
    replace: '{{ item.setting }} = {{ item.value }}'
  loop:
    - { setting: 'SEND_TO_EMAIL', value: "'{{ admin_email }}'" }
    - { setting: 'TIME_ZONE', value: "'CET'" }


# Installs system packages. Can easily be ansified.
- name: Run initial privileged deploy scripts
  tags:
  - deploy
  - deploy-init
  ansible.builtin.shell:
    chdir: '{{ jaspar_base_dir }}/jaspar2020'
    cmd: './deploy.sh -i -- -s {{ jaspar_hostname }} -d {{ jaspar_data_dir }} -S'

# Time: ca 5 min
- name: Run unprivileged deploy scripts
  tags:
  - deploy
  - deploy-user
  ansible.builtin.shell:
    chdir: '{{ jaspar_base_dir }}/jaspar2020'
    cmd: './deploy.sh -u -- -s {{ jaspar_hostname }} -d {{ jaspar_data_dir }} -S'

# Time: ca 2 min
- name: Run final privileged deploy scripts
  tags:
  - deploy
  - deploy-final
  ansible.builtin.shell:
    chdir: '{{ jaspar_base_dir }}/jaspar2020'
    cmd: './deploy.sh -f -- -s {{ jaspar_hostname }} -d {{ jaspar_data_dir }} -S'
    creates: '/etc/httpd/conf.d/{{ jaspar_hostname }}.conf'
  notify:
    - Restart httpd
    - Run tests
