---
# Create a TCP rule covering current IP
- name: Create security rule to TCP access instance
  tags: instance
  openstack.cloud.security_group_rule:
    security_group: '{{ security_group_name }}'
    protocol: tcp
    ethertype: IPv4
    remote_ip_prefix: '{{ ipv4_adress }}'
