---
# Apply label to given file/dir only if changed in the above task.
- name: Apply SELinux file contexts
  tags: selinux
  become: true
  ansible.builtin.command: 'restorecon -ir {{ jaspar_base_dir }}/{{ item.item }}'
  when: item.changed
  loop: '{{ sefcontext.results }}'

- name: Restart httpd
  become: true
  ansible.builtin.systemd:
    name: httpd.service
    state: reloaded

- name: Run website tests
  listen: Run tests
  tags: test
  ansible.builtin.command:
    chdir: '{{ jaspar_base_dir }}/jaspar2020'
    cmd: 'tests/test_website.py --url https://{{ inventory_hostname }}'

- name: Run API tests
  listen: Run tests
  tags: test
  ansible.builtin.command:
    chdir: '{{ jaspar_base_dir }}/jaspar2020'
    cmd: 'tests/test_api.py --url https://{{ inventory_hostname }}/api/v1'
