---
# Apply label to given file/dir only if changed in the above task.
- name: Apply SELinux file contexts
  tags:
    - selinux
    - jaspar
  become: true
  ansible.builtin.command: 'restorecon -ir {{ jaspar_base_dir }}/{{ item.item }}'
  when: item.changed
  loop: '{{ sefcontext.results }}'

- name: Restore SELinux file contexts
  tags:
    - selinux
    - jaspar
  become: true
  ansible.builtin.command: 'restorecon -r {{ jaspar_base_dir }}'
#  ansible.builtin.command: 'restorecon -r {{ jaspar_base_dir }}/{{ item }}'
#  loop: '{{ sef_httpd_content }}'

- name: Restart httpd
  tags:
    - jaspar
  become: true
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Run website tests
  listen: Run tests
  tags:
    - test
    - jaspar
  ansible.builtin.command:
    chdir: '{{ jaspar_base_dir }}/jaspar2020'
    cmd: 'tests/test_website.py --url https://{{ inventory_hostname }}'

- name: Run API tests
  listen: Run tests
  tags:
    - test
    - jaspar
  ansible.builtin.command:
    chdir: '{{ jaspar_base_dir }}/jaspar2020'
    cmd: 'tests/test_api.py --url https://{{ inventory_hostname }}/api/v1'
