all:
  hosts:
    test.jaspar.uiocloud.no:
      ansible_user: cloud-user
      ansible_ssh_private_key_file: ~/.ssh/jaspar-test-key.pem
      jaspar_base_dir: /data/apps
      jaspar_data_dir: /data/JASPAR_RELEASES_2022-02-11
      jaspar_data_url: 'https://frigg.uio.no/ftp/mathelier/JASPAR_RELEASES_2022-02-11/'
      certbot_admin_email: morj@uio.no
